// macOS menu-bar tray.
//
// Responsibilities:
//   * Build a single tray icon (the IronClaw claw glyph) at app start
//     and register left-click/right-click handlers.
//   * Surface a context menu — Show/Hide, Restart sidecar, Settings,
//     Quit — and re-emit menu activations as Tauri events so the JS
//     side can react (navigation, IPC into the connection store, etc.).
//   * Expose `update_status(...)` so the JS connection store can swap
//     the icon between connected / connecting / disconnected via the
//     `update_tray_status` IPC command in `lib.rs`.
//
// We deliberately keep one tray icon (created in `create`) and stash its
// id in app-state so subsequent `set_icon` swaps stay cheap. The icon
// bytes are embedded with `include_bytes!` so the binary stays
// self-contained even when distributed as a flat `.app` bundle without
// the source tree.
//
// Visibility toggling (the "Show in menu bar" preference) is handled by
// the JS layer via the existing `update_tray_status` command + a new
// `set_tray_visible` companion below. When `enabled = false` we hide the
// icon but keep the listener wiring intact so the user can re-enable
// without restarting.

use std::sync::Mutex;

use serde::{Deserialize, Serialize};
use tauri::{
    image::Image,
    menu::{Menu, MenuItem, PredefinedMenuItem, Submenu},
    tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent},
    AppHandle, Emitter, Manager, Wry,
};

/// Stable tray-icon identifier. We only ever create one tray icon per app
/// run, but having an explicit id makes `app.tray_by_id(...)` deterministic
/// when other modules (e.g. `update_status` below) need to fetch it back.
pub const TRAY_ID: &str = "ironclaw-main";

// Menu-item ids — used by both the builder and the `on_menu_event`
// dispatcher below. Keep them in one place so a typo in one spot can't
// silently break the wiring.
const MENU_ID_SHOW_HIDE: &str = "tray.show-hide";
const MENU_ID_RESTART_SIDECAR: &str = "tray.restart-sidecar";
const MENU_ID_SETTINGS: &str = "tray.settings";
/// Prefix for the per-entry "Recent notifications" submenu items. The
/// JS-supplied id is appended (`tray.recent.<uuid>`) so the menu-event
/// dispatcher can extract it back out without keeping a side table.
const MENU_ID_RECENT_PREFIX: &str = "tray.recent.";
/// Fixed id for the submenu's "Clear all" button. Constant rather than
/// dynamic so the dispatcher branch is a cheap string compare.
const MENU_ID_RECENT_CLEAR: &str = "tray.recent.__clear__";
/// Fixed id for the empty-state placeholder. Disabled in the menu so
/// clicking it is a no-op; the constant just keeps the id stable for
/// debugging.
const MENU_ID_RECENT_EMPTY: &str = "tray.recent.__empty__";
// Quit goes through `PredefinedMenuItem::quit`, which fires Tauri's
// normal exit path (RunEvent::ExitRequested) — no custom id needed.

// Tauri event names emitted to the webview when a menu item fires. The JS
// side listens via `listen('tray:...', ...)`. Strings are public-ish via
// the on-disk transcript but they're not part of any external contract.
const EVT_SHOW_WINDOW: &str = "tray:show-window";
const EVT_RESTART_SIDECAR: &str = "tray:restart-sidecar";
const EVT_SHOW_SETTINGS: &str = "tray:show-settings";
/// Click on a "Recent notifications" submenu entry. Payload is the
/// JS-supplied id; the JS-side listener looks it up in the history ring
/// to find the right surface to navigate to.
const EVT_OPEN_NOTIFICATION: &str = "tray:open-notification";
/// Click on the submenu's "Clear all" item. Payload is `()` — the
/// JS-side listener calls `notifications.clearHistory()` which will
/// push a fresh empty menu through `update_tray_recent`.
const EVT_CLEAR_NOTIFICATIONS: &str = "tray:clear-notifications";

// Status icons embedded at compile time. Generated by
// `icons/tray/build_tray_icons.py` — see that script for the design
// rationale (three colored variants vs. one template).
//
// Two families: status-only (no count overlay) and status × count
// composites. We embed all 33 variants so the badge swap is a single
// `set_icon` call against a pre-rendered PNG — no runtime compositing,
// no image-decoder cost during the hot status-change path beyond what
// Tauri's tray-icon crate already does on the first load.
//
// `Image::from_bytes` is cheap (decodes the PNG once and caches the
// raw RGBA inside Tauri's `Image<'static>`) but we still keep the slice
// table organized so adding a new variant family — e.g. an "error" hue
// or a more granular count bucket — stays a single-pass edit here +
// `build_tray_icons.py`.
const ICON_CONNECTED: &[u8] = include_bytes!("../icons/tray/tray-connected.png");
const ICON_CONNECTING: &[u8] = include_bytes!("../icons/tray/tray-connecting.png");
const ICON_DISCONNECTED: &[u8] = include_bytes!("../icons/tray/tray-disconnected.png");

// Connected × count overlays.
const ICON_CONNECTED_1: &[u8] = include_bytes!("../icons/tray/tray-connected-1.png");
const ICON_CONNECTED_2: &[u8] = include_bytes!("../icons/tray/tray-connected-2.png");
const ICON_CONNECTED_3: &[u8] = include_bytes!("../icons/tray/tray-connected-3.png");
const ICON_CONNECTED_4: &[u8] = include_bytes!("../icons/tray/tray-connected-4.png");
const ICON_CONNECTED_5: &[u8] = include_bytes!("../icons/tray/tray-connected-5.png");
const ICON_CONNECTED_6: &[u8] = include_bytes!("../icons/tray/tray-connected-6.png");
const ICON_CONNECTED_7: &[u8] = include_bytes!("../icons/tray/tray-connected-7.png");
const ICON_CONNECTED_8: &[u8] = include_bytes!("../icons/tray/tray-connected-8.png");
const ICON_CONNECTED_9: &[u8] = include_bytes!("../icons/tray/tray-connected-9.png");
const ICON_CONNECTED_9PLUS: &[u8] = include_bytes!("../icons/tray/tray-connected-9plus.png");

// Connecting × count overlays.
const ICON_CONNECTING_1: &[u8] = include_bytes!("../icons/tray/tray-connecting-1.png");
const ICON_CONNECTING_2: &[u8] = include_bytes!("../icons/tray/tray-connecting-2.png");
const ICON_CONNECTING_3: &[u8] = include_bytes!("../icons/tray/tray-connecting-3.png");
const ICON_CONNECTING_4: &[u8] = include_bytes!("../icons/tray/tray-connecting-4.png");
const ICON_CONNECTING_5: &[u8] = include_bytes!("../icons/tray/tray-connecting-5.png");
const ICON_CONNECTING_6: &[u8] = include_bytes!("../icons/tray/tray-connecting-6.png");
const ICON_CONNECTING_7: &[u8] = include_bytes!("../icons/tray/tray-connecting-7.png");
const ICON_CONNECTING_8: &[u8] = include_bytes!("../icons/tray/tray-connecting-8.png");
const ICON_CONNECTING_9: &[u8] = include_bytes!("../icons/tray/tray-connecting-9.png");
const ICON_CONNECTING_9PLUS: &[u8] = include_bytes!("../icons/tray/tray-connecting-9plus.png");

// Disconnected × count overlays.
const ICON_DISCONNECTED_1: &[u8] = include_bytes!("../icons/tray/tray-disconnected-1.png");
const ICON_DISCONNECTED_2: &[u8] = include_bytes!("../icons/tray/tray-disconnected-2.png");
const ICON_DISCONNECTED_3: &[u8] = include_bytes!("../icons/tray/tray-disconnected-3.png");
const ICON_DISCONNECTED_4: &[u8] = include_bytes!("../icons/tray/tray-disconnected-4.png");
const ICON_DISCONNECTED_5: &[u8] = include_bytes!("../icons/tray/tray-disconnected-5.png");
const ICON_DISCONNECTED_6: &[u8] = include_bytes!("../icons/tray/tray-disconnected-6.png");
const ICON_DISCONNECTED_7: &[u8] = include_bytes!("../icons/tray/tray-disconnected-7.png");
const ICON_DISCONNECTED_8: &[u8] = include_bytes!("../icons/tray/tray-disconnected-8.png");
const ICON_DISCONNECTED_9: &[u8] = include_bytes!("../icons/tray/tray-disconnected-9.png");
const ICON_DISCONNECTED_9PLUS: &[u8] =
    include_bytes!("../icons/tray/tray-disconnected-9plus.png");

/// One entry in the tray "Recent notifications" submenu. Mirrors the
/// JS `NotificationHistoryEntry` minus fields the menu doesn't render
/// (ts, category, link) — the JS side keeps the full record and uses
/// the id we round-trip back through `EVT_OPEN_NOTIFICATION` to look
/// up category-based navigation.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct RecentItem {
    pub id: String,
    pub title: String,
    /// Single-line body. Shown as a secondary text inside the submenu
    /// item label (we squash newlines on the JS side before invoking
    /// to keep the macOS menu renderer happy).
    pub body: String,
}

/// Cached recent items so `update_tray_recent` can rebuild the parent
/// menu on every call without the caller having to re-supply them.
/// Wrapped in a `Mutex` because tauri menu mutation runs on the main
/// thread but the IPC handler may dispatch from a worker.
#[derive(Default)]
pub struct RecentItemsState(pub Mutex<Vec<RecentItem>>);

/// Last-known (status, count) pair driving the tray glyph. Cached so
/// the two IPC entry points (`update_tray_status`, `update_tray_badge`)
/// can each mutate one field and re-emit the composite without the
/// caller having to round-trip the unchanged half. The unified
/// `update_status_and_count` writes both at once.
///
/// Defaults: `(Disconnected, 0)` — same starting glyph as `create()`'s
/// initial paint so a stray `update_badge(0)` before the first real
/// status push doesn't flicker the icon.
#[derive(Default)]
pub struct TrayIconState(pub Mutex<TrayIconSnapshot>);

#[derive(Debug, Clone, Copy)]
pub struct TrayIconSnapshot {
    pub status: IconStatus,
    /// Unseen-notification count, clamped to `>= 0` on write. We store
    /// the raw `i32` rather than a bucket enum so future composites
    /// (e.g. distinct 10, 50, 99+ tiers) can be added by re-bucketing
    /// in `icon_bytes` without changing the IPC contract.
    pub count: i32,
}

impl Default for TrayIconSnapshot {
    fn default() -> Self {
        Self {
            status: IconStatus::Disconnected,
            count: 0,
        }
    }
}

/// Build the tray icon, install menu + click handlers, and register it
/// against the app. Returns `Ok(())` on success; on failure the caller
/// should log and continue — a missing tray icon should never block the
/// app from launching.
pub fn create(app: &AppHandle) -> tauri::Result<()> {
    let menu = build_menu(app, &[])?;
    // Initial paint: Disconnected, no badge. The connection store will
    // push a real status through `update_tray_status` on first init,
    // and the notifications store will push the badge count via
    // `update_tray_badge` once any history is rehydrated.
    let initial_icon = load_icon(IconStatus::Disconnected, 0)?;

    let _tray = TrayIconBuilder::with_id(TRAY_ID)
        .icon(initial_icon)
        .menu(&menu)
        .tooltip("IronClaw")
        // We want the menu to appear on right-click only; left-click
        // toggles the main window (handled in `on_tray_icon_event`).
        .show_menu_on_left_click(false)
        .on_menu_event(|app, event| {
            let id = event.id().0.as_str();
            handle_menu_event(app, id);
        })
        .on_tray_icon_event(|tray, event| {
            handle_tray_icon_event(tray.app_handle(), &event);
        })
        .build(app)?;

    // Builder returns a TrayIcon, and stashing it into app state isn't
    // necessary — the tray-icon crate keeps the underlying handle alive
    // for the lifetime of the manager, and we look it back up via
    // `app.tray_by_id(TRAY_ID)` whenever we need to swap the icon.
    log::info!(target: "ironclaw_tray", "Tray icon registered (id={TRAY_ID})");
    Ok(())
}

/// Logical status the icon should reflect. Mirrors the connection store's
/// status enum but trimmed to the four states that matter at-a-glance.
#[derive(Debug, Clone, Copy)]
pub enum IconStatus {
    Connected,
    Connecting,
    Disconnected,
}

/// Swap the tray icon to reflect a new connection status. Called by the
/// `update_tray_status` IPC command in `lib.rs`. Unknown / invalid status
/// strings degrade silently to `disconnected` rather than erroring — the
/// tray is a status indicator, not a critical path.
///
/// Preserves the cached count so a status flip while a notification is
/// unseen keeps the badge overlay intact (e.g. `connecting × 3` →
/// `connected × 3` is a single icon swap, not a flicker through
/// `connected × 0`).
pub fn update_status(app: &AppHandle, status: &str) -> tauri::Result<()> {
    let next = parse_status(status);
    let count = current_count(app);
    apply_icon(app, next, count)
}

/// Show or hide the tray icon. Driven by the "Show in menu bar"
/// preference in /settings. Hidden trays keep their handle alive, so
/// flipping back to visible is instant.
pub fn set_visible(app: &AppHandle, visible: bool) -> tauri::Result<()> {
    let Some(tray) = app.tray_by_id(TRAY_ID) else {
        return Ok(());
    };
    tray.set_visible(visible)?;
    Ok(())
}

/// Replace the contents of the "Recent notifications" submenu. The
/// menu must be rebuilt as a whole rather than mutated in place because
/// the muda menu API doesn't expose per-item insertion against the
/// submenu after it's been attached to a parent. We cache the new
/// items into `RecentItemsState` so subsequent menu rebuilds (driven
/// from other surfaces in the future) can re-use the latest snapshot.
///
/// Items beyond 5 are dropped on the JS side; we still defensively cap
/// here at the same number so a buggy caller can't blow the menu out.
pub fn update_recent(app: &AppHandle, items: Vec<RecentItem>) -> tauri::Result<()> {
    let trimmed: Vec<RecentItem> = items.into_iter().take(5).collect();
    if let Some(state) = app.try_state::<RecentItemsState>() {
        if let Ok(mut guard) = state.0.lock() {
            *guard = trimmed.clone();
        }
    }
    let Some(tray) = app.tray_by_id(TRAY_ID) else {
        // Tray not registered yet. The cached items above are enough —
        // when create() runs (or runs again on a future hot path), it
        // reads from the state and seeds the menu accordingly.
        return Ok(());
    };
    let menu = build_menu(app, &trimmed)?;
    tray.set_menu(Some(menu))?;
    Ok(())
}

/// Render an unseen-notification badge into the tray icon.
///
/// Option B (composited icons): we keep one PNG per (status, count)
/// pair pre-rendered at build time (see `build_tray_icons.py`) and
/// swap whole images here instead of stamping a `set_title` text label
/// next to the glyph. The result is a fully-rendered red pill in the
/// top-right corner of the claw — closer to the native macOS menu-bar
/// look than the v1 text approach.
///
/// Caches the count in `TrayIconState` and re-composes against the
/// last-known status so a badge push without a fresh status update
/// keeps the colour stable. Also clears any leftover `set_title` text
/// from a possible pre-upgrade run so the old text badge can't sit
/// next to the new icon.
pub fn update_badge(app: &AppHandle, count: i32) -> tauri::Result<()> {
    let status = current_status(app);
    apply_icon(app, status, count)
}

/// Push both status and count in one IPC call.
///
/// Used by surfaces that have both pieces of state on hand and want to
/// avoid the implicit cache reads inside the single-field setters. The
/// behaviour is identical to calling `update_status` + `update_badge`
/// in sequence: the cache lands on (status, count) and the composite
/// icon is repainted once.
pub fn update_status_and_count(
    app: &AppHandle,
    status: &str,
    count: i32,
) -> tauri::Result<()> {
    let next = parse_status(status);
    apply_icon(app, next, count)
}

// ---- internals -----------------------------------------------------------

fn build_menu(app: &AppHandle, recent: &[RecentItem]) -> tauri::Result<Menu<Wry>> {
    // Item ordering matches the spec: window toggle first, then the
    // sidecar action, recent-notifications submenu, settings, then
    // quit. A separator above the destructive Quit keeps the chrome
    // consistent with macOS apps.
    let show_hide = MenuItem::with_id(
        app,
        MENU_ID_SHOW_HIDE,
        "Show / Hide IronClaw",
        true,
        None::<&str>,
    )?;
    let restart_sidecar = MenuItem::with_id(
        app,
        MENU_ID_RESTART_SIDECAR,
        "Restart sidecar",
        true,
        None::<&str>,
    )?;
    let recent_submenu = build_recent_submenu(app, recent)?;
    let settings = MenuItem::with_id(
        app,
        MENU_ID_SETTINGS,
        "Open Settings",
        true,
        None::<&str>,
    )?;
    let separator = PredefinedMenuItem::separator(app)?;
    // Predefined `quit` fires the app's normal exit path (RunEvent::ExitRequested),
    // so our sidecar shutdown hook in `lib.rs` runs as expected.
    let quit = PredefinedMenuItem::quit(app, Some("Quit IronClaw"))?;

    Menu::with_items(
        app,
        &[
            &show_hide,
            &restart_sidecar,
            &recent_submenu,
            &settings,
            &separator,
            &quit,
        ],
    )
}

/// Build the "Recent notifications" submenu. When `recent` is empty we
/// render a single disabled "No recent notifications" placeholder so
/// the submenu still opens (instead of disappearing or showing a blank
/// rectangle, which would feel broken). When entries exist we render
/// them in the order supplied (JS sends newest-first), append a
/// separator, then the "Clear all" item. The item label uses the
/// notification title; macOS does not give us a built-in
/// secondary-text affordance for menu items, so we splice the body in
/// after the title with an en-dash separator when non-empty. Tooltip
/// support on tray submenus is not exposed by the muda menu API at the
/// version we ship, so the en-dash composition is the next-best
/// information-density bump.
fn build_recent_submenu(
    app: &AppHandle,
    recent: &[RecentItem],
) -> tauri::Result<Submenu<Wry>> {
    let submenu = Submenu::with_id(app, "tray.recent", "Recent notifications", true)?;

    if recent.is_empty() {
        let placeholder = MenuItem::with_id(
            app,
            MENU_ID_RECENT_EMPTY,
            "No recent notifications",
            false,
            None::<&str>,
        )?;
        submenu.append(&placeholder)?;
        return Ok(submenu);
    }

    for item in recent {
        let label = compose_recent_label(&item.title, &item.body);
        let id = format!("{MENU_ID_RECENT_PREFIX}{}", item.id);
        let entry = MenuItem::with_id(app, &id, label, true, None::<&str>)?;
        submenu.append(&entry)?;
    }
    let sep = PredefinedMenuItem::separator(app)?;
    submenu.append(&sep)?;
    let clear = MenuItem::with_id(app, MENU_ID_RECENT_CLEAR, "Clear all", true, None::<&str>)?;
    submenu.append(&clear)?;

    Ok(submenu)
}

/// Cap the body at a reasonable single-line length so the menu doesn't
/// stretch the whole menu bar. macOS lets menu items be wide enough to
/// hold long strings, but we want the menu chrome to stay readable —
/// 60 chars is roughly two-thirds of a normal Mac status menu width.
fn compose_recent_label(title: &str, body: &str) -> String {
    if body.is_empty() {
        return title.to_string();
    }
    const MAX_BODY: usize = 60;
    let trimmed = if body.chars().count() > MAX_BODY {
        let mut s: String = body.chars().take(MAX_BODY).collect();
        s.push('…');
        s
    } else {
        body.to_string()
    };
    format!("{title} — {trimmed}")
}

/// Dispatch a tray menu activation. We translate the menu item id into a
/// Tauri event so the JS layer (which already owns navigation and the
/// connection store) can take it from there.
fn handle_menu_event(app: &AppHandle, id: &str) {
    match id {
        MENU_ID_SHOW_HIDE => toggle_main_window(app),
        MENU_ID_RESTART_SIDECAR => {
            let _ = app.emit(EVT_RESTART_SIDECAR, ());
            focus_main_window(app);
        }
        MENU_ID_SETTINGS => {
            let _ = app.emit(EVT_SHOW_SETTINGS, ());
            focus_main_window(app);
        }
        MENU_ID_RECENT_CLEAR => {
            // No window-focus on clear: it's a passive list operation,
            // not a navigation. The JS-side listener calls
            // `notifications.clearHistory()` which will push a fresh
            // empty menu through `update_tray_recent`.
            let _ = app.emit(EVT_CLEAR_NOTIFICATIONS, ());
        }
        // "Recent notifications" entries — the dynamic ids carry the
        // notification's history id after the prefix. Empty-state and
        // separator items never reach this branch (the empty entry is
        // disabled; the separator has no id).
        other if other.starts_with(MENU_ID_RECENT_PREFIX) => {
            // Skip the sentinel ids — the empty placeholder is disabled
            // and shouldn't fire, but a future menu API change might
            // start delivering events for disabled items, so we
            // belt-and-braces it here.
            if other == MENU_ID_RECENT_EMPTY {
                return;
            }
            let notification_id = &other[MENU_ID_RECENT_PREFIX.len()..];
            let _ = app.emit(EVT_OPEN_NOTIFICATION, notification_id.to_string());
            focus_main_window(app);
        }
        // MENU_ID_QUIT is handled by PredefinedMenuItem::quit — no
        // manual dispatch needed.
        _ => {}
    }
}

/// Mouse-click handler on the tray icon body (not the menu). Left-click
/// toggles the main window; everything else falls through to whatever
/// macOS does by default (right-click already opens the menu since we
/// passed `show_menu_on_left_click(false)`).
fn handle_tray_icon_event(app: &AppHandle, event: &TrayIconEvent) {
    if let TrayIconEvent::Click {
        button: MouseButton::Left,
        button_state: MouseButtonState::Up,
        ..
    } = event
    {
        toggle_main_window(app);
    }
}

/// Show + focus the main window if hidden, hide it if currently visible
/// and focused. Defensive: ignores errors so a half-broken window
/// never panics the tray click.
fn toggle_main_window(app: &AppHandle) {
    let Some(window) = app.get_webview_window("main") else {
        return;
    };
    let visible = window.is_visible().unwrap_or(false);
    if visible {
        let _ = window.hide();
    } else {
        let _ = window.show();
        let _ = window.set_focus();
        // Emit so the JS layer can react (e.g. refresh, scroll to top).
        let _ = app.emit(EVT_SHOW_WINDOW, ());
    }
}

fn focus_main_window(app: &AppHandle) {
    let Some(window) = app.get_webview_window("main") else {
        return;
    };
    let _ = window.show();
    let _ = window.set_focus();
}

fn load_icon(status: IconStatus, count: i32) -> tauri::Result<Image<'static>> {
    Image::from_bytes(icon_bytes(status, count))
}

/// Resolve a (status, count) pair to the matching embedded PNG slice.
///
/// `count <= 0` selects the status-only variant (no badge overlay).
/// `count >= 10` collapses to the `9plus` variant so the badge pill
/// never grows past two glyphs at menu-bar resolution. Everything in
/// between picks its exact PNG.
fn icon_bytes(status: IconStatus, count: i32) -> &'static [u8] {
    match (status, count) {
        (IconStatus::Connected, c) if c <= 0 => ICON_CONNECTED,
        (IconStatus::Connected, 1) => ICON_CONNECTED_1,
        (IconStatus::Connected, 2) => ICON_CONNECTED_2,
        (IconStatus::Connected, 3) => ICON_CONNECTED_3,
        (IconStatus::Connected, 4) => ICON_CONNECTED_4,
        (IconStatus::Connected, 5) => ICON_CONNECTED_5,
        (IconStatus::Connected, 6) => ICON_CONNECTED_6,
        (IconStatus::Connected, 7) => ICON_CONNECTED_7,
        (IconStatus::Connected, 8) => ICON_CONNECTED_8,
        (IconStatus::Connected, 9) => ICON_CONNECTED_9,
        (IconStatus::Connected, _) => ICON_CONNECTED_9PLUS,

        (IconStatus::Connecting, c) if c <= 0 => ICON_CONNECTING,
        (IconStatus::Connecting, 1) => ICON_CONNECTING_1,
        (IconStatus::Connecting, 2) => ICON_CONNECTING_2,
        (IconStatus::Connecting, 3) => ICON_CONNECTING_3,
        (IconStatus::Connecting, 4) => ICON_CONNECTING_4,
        (IconStatus::Connecting, 5) => ICON_CONNECTING_5,
        (IconStatus::Connecting, 6) => ICON_CONNECTING_6,
        (IconStatus::Connecting, 7) => ICON_CONNECTING_7,
        (IconStatus::Connecting, 8) => ICON_CONNECTING_8,
        (IconStatus::Connecting, 9) => ICON_CONNECTING_9,
        (IconStatus::Connecting, _) => ICON_CONNECTING_9PLUS,

        (IconStatus::Disconnected, c) if c <= 0 => ICON_DISCONNECTED,
        (IconStatus::Disconnected, 1) => ICON_DISCONNECTED_1,
        (IconStatus::Disconnected, 2) => ICON_DISCONNECTED_2,
        (IconStatus::Disconnected, 3) => ICON_DISCONNECTED_3,
        (IconStatus::Disconnected, 4) => ICON_DISCONNECTED_4,
        (IconStatus::Disconnected, 5) => ICON_DISCONNECTED_5,
        (IconStatus::Disconnected, 6) => ICON_DISCONNECTED_6,
        (IconStatus::Disconnected, 7) => ICON_DISCONNECTED_7,
        (IconStatus::Disconnected, 8) => ICON_DISCONNECTED_8,
        (IconStatus::Disconnected, 9) => ICON_DISCONNECTED_9,
        (IconStatus::Disconnected, _) => ICON_DISCONNECTED_9PLUS,
    }
}

/// Composite swap: write the new (status, count) into the cache, then
/// repaint the tray icon. Clears any leftover `set_title` text so a
/// pre-upgrade text badge can't sit next to the new pill icon.
///
/// Silently no-ops when the tray isn't registered (`set_visible(false)`
/// keeps the handle alive, so this only triggers if the create-hook
/// failed). Tray IPC is decorative; we never propagate a missing-tray
/// error up to the JS caller.
fn apply_icon(app: &AppHandle, status: IconStatus, count: i32) -> tauri::Result<()> {
    // Cache the new snapshot first so a subsequent single-field setter
    // sees the latest values even if the icon repaint below fails.
    if let Some(state) = app.try_state::<TrayIconState>() {
        if let Ok(mut guard) = state.0.lock() {
            *guard = TrayIconSnapshot {
                status,
                count: count.max(0),
            };
        }
    }
    let Some(tray) = app.tray_by_id(TRAY_ID) else {
        return Ok(());
    };
    let icon = load_icon(status, count)?;
    tray.set_icon(Some(icon))?;
    // Clear any leftover text title from the v1 (option-A) badge path.
    // Idempotent — setting None on an already-empty title is a no-op
    // and doesn't trigger a repaint in the tray-icon crate.
    tray.set_title(None::<&str>)?;
    Ok(())
}

/// Read the cached status, falling back to `Disconnected` when the
/// state hasn't been registered yet (e.g. unit-test contexts without
/// the full setup hook).
fn current_status(app: &AppHandle) -> IconStatus {
    app.try_state::<TrayIconState>()
        .and_then(|s| s.0.lock().ok().map(|g| g.status))
        .unwrap_or(IconStatus::Disconnected)
}

/// Read the cached count, falling back to `0` (no badge) when the
/// state hasn't been registered yet.
fn current_count(app: &AppHandle) -> i32 {
    app.try_state::<TrayIconState>()
        .and_then(|s| s.0.lock().ok().map(|g| g.count))
        .unwrap_or(0)
}

fn parse_status(s: &str) -> IconStatus {
    match s {
        "connected" => IconStatus::Connected,
        "connecting" => IconStatus::Connecting,
        // Treat "error" and "disconnected" identically — both should
        // draw the user's attention to the menu bar; we surface the
        // distinction in the sidebar pill and toast layer.
        _ => IconStatus::Disconnected,
    }
}
