// macOS menu-bar tray.
//
// Responsibilities:
//   * Build a single tray icon (the IronClaw claw glyph) at app start
//     and register left-click/right-click handlers.
//   * Surface a context menu — Show/Hide, Restart sidecar, Settings,
//     Quit — and re-emit menu activations as Tauri events so the JS
//     side can react (navigation, IPC into the connection store, etc.).
//   * Expose `update_status(...)` so the JS connection store can swap
//     the icon between connected / connecting / disconnected via the
//     `update_tray_status` IPC command in `lib.rs`.
//
// We deliberately keep one tray icon (created in `create`) and stash its
// id in app-state so subsequent `set_icon` swaps stay cheap. The icon
// bytes are embedded with `include_bytes!` so the binary stays
// self-contained even when distributed as a flat `.app` bundle without
// the source tree.
//
// Visibility toggling (the "Show in menu bar" preference) is handled by
// the JS layer via the existing `update_tray_status` command + a new
// `set_tray_visible` companion below. When `enabled = false` we hide the
// icon but keep the listener wiring intact so the user can re-enable
// without restarting.

use tauri::{
    image::Image,
    menu::{Menu, MenuItem, PredefinedMenuItem},
    tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent},
    AppHandle, Emitter, Manager, Wry,
};

/// Stable tray-icon identifier. We only ever create one tray icon per app
/// run, but having an explicit id makes `app.tray_by_id(...)` deterministic
/// when other modules (e.g. `update_status` below) need to fetch it back.
pub const TRAY_ID: &str = "ironclaw-main";

// Menu-item ids — used by both the builder and the `on_menu_event`
// dispatcher below. Keep them in one place so a typo in one spot can't
// silently break the wiring.
const MENU_ID_SHOW_HIDE: &str = "tray.show-hide";
const MENU_ID_RESTART_SIDECAR: &str = "tray.restart-sidecar";
const MENU_ID_SETTINGS: &str = "tray.settings";
// Quit goes through `PredefinedMenuItem::quit`, which fires Tauri's
// normal exit path (RunEvent::ExitRequested) — no custom id needed.

// Tauri event names emitted to the webview when a menu item fires. The JS
// side listens via `listen('tray:...', ...)`. Strings are public-ish via
// the on-disk transcript but they're not part of any external contract.
const EVT_SHOW_WINDOW: &str = "tray:show-window";
const EVT_RESTART_SIDECAR: &str = "tray:restart-sidecar";
const EVT_SHOW_SETTINGS: &str = "tray:show-settings";

// Status icons embedded at compile time. Generated by
// `icons/tray/build_tray_icons.py` — see that script for the design
// rationale (three colored variants vs. one template).
const ICON_CONNECTED: &[u8] = include_bytes!("../icons/tray/tray-connected.png");
const ICON_CONNECTING: &[u8] = include_bytes!("../icons/tray/tray-connecting.png");
const ICON_DISCONNECTED: &[u8] = include_bytes!("../icons/tray/tray-disconnected.png");

/// Build the tray icon, install menu + click handlers, and register it
/// against the app. Returns `Ok(())` on success; on failure the caller
/// should log and continue — a missing tray icon should never block the
/// app from launching.
pub fn create(app: &AppHandle) -> tauri::Result<()> {
    let menu = build_menu(app)?;
    let initial_icon = load_icon(IconStatus::Disconnected)?;

    let _tray = TrayIconBuilder::with_id(TRAY_ID)
        .icon(initial_icon)
        .menu(&menu)
        .tooltip("IronClaw")
        // We want the menu to appear on right-click only; left-click
        // toggles the main window (handled in `on_tray_icon_event`).
        .show_menu_on_left_click(false)
        .on_menu_event(|app, event| {
            let id = event.id().0.as_str();
            handle_menu_event(app, id);
        })
        .on_tray_icon_event(|tray, event| {
            handle_tray_icon_event(tray.app_handle(), &event);
        })
        .build(app)?;

    // Builder returns a TrayIcon, and stashing it into app state isn't
    // necessary — the tray-icon crate keeps the underlying handle alive
    // for the lifetime of the manager, and we look it back up via
    // `app.tray_by_id(TRAY_ID)` whenever we need to swap the icon.
    Ok(())
}

/// Logical status the icon should reflect. Mirrors the connection store's
/// status enum but trimmed to the four states that matter at-a-glance.
#[derive(Debug, Clone, Copy)]
enum IconStatus {
    Connected,
    Connecting,
    Disconnected,
}

/// Swap the tray icon to reflect a new connection status. Called by the
/// `update_tray_status` IPC command in `lib.rs`. Unknown / invalid status
/// strings degrade silently to `disconnected` rather than erroring — the
/// tray is a status indicator, not a critical path.
pub fn update_status(app: &AppHandle, status: &str) -> tauri::Result<()> {
    let next = parse_status(status);
    let Some(tray) = app.tray_by_id(TRAY_ID) else {
        // Tray not registered (e.g. setup hook failed silently or the
        // user hid it via the preference). Nothing to do.
        return Ok(());
    };
    let icon = load_icon(next)?;
    tray.set_icon(Some(icon))?;
    Ok(())
}

/// Show or hide the tray icon. Driven by the "Show in menu bar"
/// preference in /settings. Hidden trays keep their handle alive, so
/// flipping back to visible is instant.
pub fn set_visible(app: &AppHandle, visible: bool) -> tauri::Result<()> {
    let Some(tray) = app.tray_by_id(TRAY_ID) else {
        return Ok(());
    };
    tray.set_visible(visible)?;
    Ok(())
}

/// Render an unseen-notification badge next to the tray icon.
///
/// Option A from the spec: we use macOS's native menu-bar title support
/// (`TrayIcon::set_title`) so the count renders as text next to the icon
/// — no image compositing, no per-(status, count) icon variants. `count`
/// values greater than 9 collapse to `"9+"` so the title never grows
/// wider than two glyphs in the menu bar; `count <= 0` clears the title
/// so the icon sits flush against the surrounding chrome.
///
/// TODO(option B): swap for runtime-composited icons (status × count
/// variants generated by overlaying a numbered badge on the existing PNG
/// trio) once we want a fully native-looking pill instead of plain text.
/// That path is heavier (one icon per pair, image decoder + compositor
/// at startup), so we keep the simpler title approach for v1.
pub fn update_badge(app: &AppHandle, count: i32) -> tauri::Result<()> {
    let Some(tray) = app.tray_by_id(TRAY_ID) else {
        // No tray registered (icon hidden via preference, or setup hook
        // failed silently). Nothing to do — when/if the tray comes back
        // the JS store will push the current count through again.
        return Ok(());
    };
    if count <= 0 {
        tray.set_title(None::<&str>)?;
    } else {
        let label = if count > 9 {
            "9+".to_string()
        } else {
            count.to_string()
        };
        tray.set_title(Some(label))?;
    }
    Ok(())
}

// ---- internals -----------------------------------------------------------

fn build_menu(app: &AppHandle) -> tauri::Result<Menu<Wry>> {
    // Item ordering matches the spec: window toggle first, then the
    // sidecar action, then settings, then quit. A separator above the
    // destructive Quit keeps the chrome consistent with macOS apps.
    let show_hide = MenuItem::with_id(
        app,
        MENU_ID_SHOW_HIDE,
        "Show / Hide IronClaw",
        true,
        None::<&str>,
    )?;
    let restart_sidecar = MenuItem::with_id(
        app,
        MENU_ID_RESTART_SIDECAR,
        "Restart sidecar",
        true,
        None::<&str>,
    )?;
    let settings = MenuItem::with_id(
        app,
        MENU_ID_SETTINGS,
        "Open Settings",
        true,
        None::<&str>,
    )?;
    let separator = PredefinedMenuItem::separator(app)?;
    // Predefined `quit` fires the app's normal exit path (RunEvent::ExitRequested),
    // so our sidecar shutdown hook in `lib.rs` runs as expected.
    let quit = PredefinedMenuItem::quit(app, Some("Quit IronClaw"))?;

    Menu::with_items(
        app,
        &[&show_hide, &restart_sidecar, &settings, &separator, &quit],
    )
}

/// Dispatch a tray menu activation. We translate the menu item id into a
/// Tauri event so the JS layer (which already owns navigation and the
/// connection store) can take it from there.
fn handle_menu_event(app: &AppHandle, id: &str) {
    match id {
        MENU_ID_SHOW_HIDE => toggle_main_window(app),
        MENU_ID_RESTART_SIDECAR => {
            let _ = app.emit(EVT_RESTART_SIDECAR, ());
            focus_main_window(app);
        }
        MENU_ID_SETTINGS => {
            let _ = app.emit(EVT_SHOW_SETTINGS, ());
            focus_main_window(app);
        }
        // MENU_ID_QUIT is handled by PredefinedMenuItem::quit — no
        // manual dispatch needed.
        _ => {}
    }
}

/// Mouse-click handler on the tray icon body (not the menu). Left-click
/// toggles the main window; everything else falls through to whatever
/// macOS does by default (right-click already opens the menu since we
/// passed `show_menu_on_left_click(false)`).
fn handle_tray_icon_event(app: &AppHandle, event: &TrayIconEvent) {
    if let TrayIconEvent::Click {
        button: MouseButton::Left,
        button_state: MouseButtonState::Up,
        ..
    } = event
    {
        toggle_main_window(app);
    }
}

/// Show + focus the main window if hidden, hide it if currently visible
/// and focused. Defensive: ignores errors so a half-broken window
/// never panics the tray click.
fn toggle_main_window(app: &AppHandle) {
    let Some(window) = app.get_webview_window("main") else {
        return;
    };
    let visible = window.is_visible().unwrap_or(false);
    if visible {
        let _ = window.hide();
    } else {
        let _ = window.show();
        let _ = window.set_focus();
        // Emit so the JS layer can react (e.g. refresh, scroll to top).
        let _ = app.emit(EVT_SHOW_WINDOW, ());
    }
}

fn focus_main_window(app: &AppHandle) {
    let Some(window) = app.get_webview_window("main") else {
        return;
    };
    let _ = window.show();
    let _ = window.set_focus();
}

fn load_icon(status: IconStatus) -> tauri::Result<Image<'static>> {
    let bytes: &[u8] = match status {
        IconStatus::Connected => ICON_CONNECTED,
        IconStatus::Connecting => ICON_CONNECTING,
        IconStatus::Disconnected => ICON_DISCONNECTED,
    };
    Image::from_bytes(bytes)
}

fn parse_status(s: &str) -> IconStatus {
    match s {
        "connected" => IconStatus::Connected,
        "connecting" => IconStatus::Connecting,
        // Treat "error" and "disconnected" identically — both should
        // draw the user's attention to the menu bar; we surface the
        // distinction in the sidebar pill and toast layer.
        _ => IconStatus::Disconnected,
    }
}
